"""M69/M78 — Job Data Model. Static dataset of realistic job listings."""

JOBS = [
    # ── Software Engineering ──────────────────────────────────────
    {
        "id": "job_1",
        "title": "Backend Engineer",
        "company": "TechCorp",
        "location": "Remote",
        "remote": True,
        "skills": ["python", "flask", "api", "sql", "docker"],
        "description": "Build APIs and backend systems for a growing SaaS platform.",
    },
    {
        "id": "job_2",
        "title": "Frontend Developer",
        "company": "PixelWorks",
        "location": "New York, NY",
        "remote": False,
        "skills": ["javascript", "react", "css", "html", "typescript"],
        "description": "Create responsive user interfaces and improve UX across web apps.",
    },
    {
        "id": "job_3",
        "title": "Full Stack Developer",
        "company": "LaunchPad Inc",
        "location": "San Francisco, CA",
        "remote": False,
        "skills": ["python", "javascript", "react", "flask", "sql", "api"],
        "description": "Build end-to-end features across frontend and backend systems.",
    },
    {
        "id": "job_4",
        "title": "Software Engineer",
        "company": "CoreStack",
        "location": "Denver, CO",
        "remote": False,
        "skills": ["python", "java", "api", "sql", "git", "testing"],
        "description": "Design and implement scalable software solutions across the stack.",
    },
    {
        "id": "job_5",
        "title": "Senior Backend Engineer",
        "company": "ScaleUp",
        "location": "Remote",
        "remote": True,
        "skills": ["python", "django", "api", "sql", "docker", "kubernetes"],
        "description": "Architect high-throughput backend services for millions of users.",
    },
    {
        "id": "job_6",
        "title": "Junior Software Developer",
        "company": "CodeStart",
        "location": "Austin, TX",
        "remote": False,
        "skills": ["python", "javascript", "git", "html", "css"],
        "description": "Join a mentorship-driven team building internal tools and web apps.",
    },
    {
        "id": "job_7",
        "title": "Mobile Developer",
        "company": "AppForge",
        "location": "Los Angeles, CA",
        "remote": False,
        "skills": ["react native", "javascript", "typescript", "api", "git"],
        "description": "Build and maintain cross-platform mobile applications.",
    },
    {
        "id": "job_8",
        "title": "API Developer",
        "company": "Connectify",
        "location": "Remote",
        "remote": True,
        "skills": ["python", "flask", "api", "rest", "graphql", "sql"],
        "description": "Design and maintain public and internal APIs for a fintech platform.",
    },
    {
        "id": "job_9",
        "title": "Embedded Systems Engineer",
        "company": "HardwareCo",
        "location": "Detroit, MI",
        "remote": False,
        "skills": ["c", "c++", "embedded", "linux", "testing"],
        "description": "Develop firmware and embedded software for IoT devices.",
    },
    # ── DevOps / Cloud ────────────────────────────────────────────
    {
        "id": "job_10",
        "title": "DevOps Engineer",
        "company": "CloudNine",
        "location": "Remote",
        "remote": True,
        "skills": ["docker", "kubernetes", "aws", "ci/cd", "linux", "python"],
        "description": "Manage cloud infrastructure, CI/CD pipelines, and deployment automation.",
    },
    {
        "id": "job_11",
        "title": "Cloud Architect",
        "company": "SkyBridge Tech",
        "location": "Remote",
        "remote": True,
        "skills": ["aws", "azure", "kubernetes", "docker", "networking", "security"],
        "description": "Design scalable cloud architectures and guide migration strategies.",
    },
    {
        "id": "job_12",
        "title": "Site Reliability Engineer",
        "company": "UptimeFirst",
        "location": "Seattle, WA",
        "remote": False,
        "skills": ["python", "kubernetes", "aws", "monitoring", "linux", "ci/cd"],
        "description": "Ensure 99.99% uptime through monitoring, automation, and incident response.",
    },
    {
        "id": "job_13",
        "title": "Platform Engineer",
        "company": "BuildStack",
        "location": "Remote",
        "remote": True,
        "skills": ["terraform", "docker", "kubernetes", "aws", "python", "ci/cd"],
        "description": "Build and maintain the internal developer platform and tooling.",
    },
    # ── Data / Analytics ──────────────────────────────────────────
    {
        "id": "job_14",
        "title": "Data Analyst",
        "company": "InsightHub",
        "location": "Remote",
        "remote": True,
        "skills": ["python", "sql", "excel", "tableau", "statistics"],
        "description": "Analyze business data, build dashboards, and deliver actionable insights.",
    },
    {
        "id": "job_15",
        "title": "Data Scientist",
        "company": "Predictive Labs",
        "location": "Boston, MA",
        "remote": False,
        "skills": [
            "python",
            "machine learning",
            "sql",
            "statistics",
            "pandas",
            "tensorflow",
        ],
        "description": "Build predictive models and run experiments to drive product decisions.",
    },
    {
        "id": "job_16",
        "title": "Machine Learning Engineer",
        "company": "AI Dynamics",
        "location": "Remote",
        "remote": True,
        "skills": ["python", "machine learning", "tensorflow", "docker", "api", "sql"],
        "description": "Deploy and optimize ML models in production environments.",
    },
    {
        "id": "job_17",
        "title": "Data Engineer",
        "company": "DataPipe Inc",
        "location": "Chicago, IL",
        "remote": False,
        "skills": ["python", "sql", "spark", "airflow", "aws", "etl"],
        "description": "Build and maintain data pipelines that power analytics and ML teams.",
    },
    {
        "id": "job_18",
        "title": "Senior Data Analyst",
        "company": "MetricsPlus",
        "location": "Remote",
        "remote": True,
        "skills": ["sql", "python", "tableau", "statistics", "excel", "reporting"],
        "description": "Lead data storytelling and executive reporting for a growth-stage startup.",
    },
    {
        "id": "job_19",
        "title": "BI Developer",
        "company": "DashView",
        "location": "Dallas, TX",
        "remote": False,
        "skills": ["sql", "power bi", "excel", "etl", "reporting"],
        "description": "Design and maintain BI dashboards and automated reporting solutions.",
    },
    # ── QA / Testing ──────────────────────────────────────────────
    {
        "id": "job_20",
        "title": "QA Engineer",
        "company": "QualityFirst",
        "location": "Remote",
        "remote": True,
        "skills": ["testing", "selenium", "python", "api", "ci/cd"],
        "description": "Develop automated test suites and ensure product quality before release.",
    },
    {
        "id": "job_21",
        "title": "SDET",
        "company": "TestDriven Labs",
        "location": "Remote",
        "remote": True,
        "skills": ["python", "testing", "api", "ci/cd", "docker", "selenium"],
        "description": "Build test frameworks and integrate quality checks into CI pipelines.",
    },
    # ── Product / Project Management ──────────────────────────────
    {
        "id": "job_22",
        "title": "Product Manager",
        "company": "BuildRight",
        "location": "Austin, TX",
        "remote": False,
        "skills": [
            "product strategy",
            "agile",
            "analytics",
            "roadmapping",
            "stakeholder management",
        ],
        "description": "Define product vision, prioritize features, and work with engineering teams.",
    },
    {
        "id": "job_23",
        "title": "Project Manager",
        "company": "DeliverNow",
        "location": "Remote",
        "remote": True,
        "skills": [
            "project management",
            "agile",
            "stakeholder management",
            "risk management",
            "reporting",
        ],
        "description": "Lead cross-functional projects from planning through delivery.",
    },
    {
        "id": "job_24",
        "title": "Technical Program Manager",
        "company": "BigScale Corp",
        "location": "San Jose, CA",
        "remote": False,
        "skills": [
            "program management",
            "agile",
            "stakeholder management",
            "api",
            "risk management",
        ],
        "description": "Coordinate multi-team technical programs and manage dependencies.",
    },
    {
        "id": "job_25",
        "title": "Scrum Master",
        "company": "AgileWorks",
        "location": "Remote",
        "remote": True,
        "skills": [
            "agile",
            "scrum",
            "facilitation",
            "stakeholder management",
            "reporting",
        ],
        "description": "Facilitate agile ceremonies, remove blockers, and coach engineering teams.",
    },
    # ── Design / UX ───────────────────────────────────────────────
    {
        "id": "job_26",
        "title": "UX Designer",
        "company": "DesignFirst",
        "location": "Seattle, WA",
        "remote": False,
        "skills": ["figma", "user research", "wireframing", "prototyping", "css"],
        "description": "Design intuitive user experiences through research, prototyping, and testing.",
    },
    {
        "id": "job_27",
        "title": "UI/UX Designer",
        "company": "BrightPixel",
        "location": "Remote",
        "remote": True,
        "skills": ["figma", "css", "html", "design systems", "prototyping"],
        "description": "Create beautiful, accessible interfaces for web and mobile products.",
    },
    {
        "id": "job_28",
        "title": "Product Designer",
        "company": "CraftLab",
        "location": "New York, NY",
        "remote": False,
        "skills": [
            "figma",
            "user research",
            "prototyping",
            "design systems",
            "analytics",
        ],
        "description": "Own end-to-end product design from user research to final handoff.",
    },
    # ── Marketing ─────────────────────────────────────────────────
    {
        "id": "job_29",
        "title": "Marketing Manager",
        "company": "GrowthEngine",
        "location": "Remote",
        "remote": True,
        "skills": [
            "digital marketing",
            "seo",
            "analytics",
            "content strategy",
            "social media",
        ],
        "description": "Plan and execute marketing campaigns to drive user acquisition and retention.",
    },
    {
        "id": "job_30",
        "title": "Content Strategist",
        "company": "WordCraft",
        "location": "Portland, OR",
        "remote": False,
        "skills": [
            "content strategy",
            "seo",
            "copywriting",
            "analytics",
            "social media",
        ],
        "description": "Develop and manage content programs that drive engagement and growth.",
    },
    {
        "id": "job_31",
        "title": "SEO Specialist",
        "company": "RankUp",
        "location": "Remote",
        "remote": True,
        "skills": ["seo", "analytics", "content strategy", "html", "keyword research"],
        "description": "Improve organic search rankings and develop link-building strategies.",
    },
    {
        "id": "job_32",
        "title": "Growth Marketing Analyst",
        "company": "FunnelMetrics",
        "location": "Remote",
        "remote": True,
        "skills": ["analytics", "sql", "digital marketing", "a/b testing", "reporting"],
        "description": "Analyze acquisition funnels, run experiments, and optimize conversion rates.",
    },
    {
        "id": "job_33",
        "title": "Social Media Manager",
        "company": "BuzzReach",
        "location": "Miami, FL",
        "remote": False,
        "skills": [
            "social media",
            "content strategy",
            "analytics",
            "copywriting",
            "video editing",
        ],
        "description": "Manage brand presence across social platforms and grow engaged audiences.",
    },
    # ── Business / Operations ─────────────────────────────────────
    {
        "id": "job_34",
        "title": "Business Analyst",
        "company": "StratCo",
        "location": "Chicago, IL",
        "remote": False,
        "skills": [
            "sql",
            "excel",
            "requirements analysis",
            "stakeholder management",
            "reporting",
        ],
        "description": "Gather requirements, analyze workflows, and bridge business and technology teams.",
    },
    {
        "id": "job_35",
        "title": "Sales Operations Analyst",
        "company": "RevOps Co",
        "location": "New York, NY",
        "remote": False,
        "skills": ["salesforce", "excel", "sql", "reporting", "analytics"],
        "description": "Optimize sales processes, maintain CRM data, and produce pipeline reports.",
    },
    {
        "id": "job_36",
        "title": "Operations Manager",
        "company": "StreamlineOps",
        "location": "Remote",
        "remote": True,
        "skills": [
            "operations",
            "project management",
            "analytics",
            "reporting",
            "stakeholder management",
        ],
        "description": "Streamline business processes and manage cross-departmental operations.",
    },
    {
        "id": "job_37",
        "title": "Financial Analyst",
        "company": "CapitalView",
        "location": "New York, NY",
        "remote": False,
        "skills": ["excel", "financial modeling", "sql", "reporting", "analytics"],
        "description": "Build financial models, analyze performance, and support strategic planning.",
    },
    {
        "id": "job_38",
        "title": "Management Consultant",
        "company": "ClearPath Advisory",
        "location": "Washington, DC",
        "remote": False,
        "skills": [
            "strategy",
            "analytics",
            "stakeholder management",
            "excel",
            "presentation",
        ],
        "description": "Advise clients on organizational strategy, operations, and transformation.",
    },
    # ── Customer / Support ────────────────────────────────────────
    {
        "id": "job_39",
        "title": "Customer Success Manager",
        "company": "RetainCo",
        "location": "Remote",
        "remote": True,
        "skills": [
            "customer success",
            "analytics",
            "stakeholder management",
            "reporting",
            "crm",
        ],
        "description": "Drive product adoption, reduce churn, and build long-term customer relationships.",
    },
    {
        "id": "job_40",
        "title": "Technical Support Engineer",
        "company": "HelpDeskPro",
        "location": "Remote",
        "remote": True,
        "skills": ["troubleshooting", "sql", "api", "linux", "communication"],
        "description": "Resolve complex technical issues and collaborate with engineering on bug fixes.",
    },
    # ── Security ──────────────────────────────────────────────────
    {
        "id": "job_41",
        "title": "Security Engineer",
        "company": "ShieldTech",
        "location": "Remote",
        "remote": True,
        "skills": ["security", "python", "linux", "networking", "aws", "docker"],
        "description": "Implement security controls, conduct audits, and respond to incidents.",
    },
    {
        "id": "job_42",
        "title": "Cybersecurity Analyst",
        "company": "Fortress Digital",
        "location": "Atlanta, GA",
        "remote": False,
        "skills": ["security", "monitoring", "networking", "linux", "risk management"],
        "description": "Monitor threats, investigate incidents, and improve security posture.",
    },
    # ── Specialized Engineering ───────────────────────────────────
    {
        "id": "job_43",
        "title": "Database Administrator",
        "company": "DataGuard",
        "location": "Remote",
        "remote": True,
        "skills": ["sql", "database administration", "python", "aws", "monitoring"],
        "description": "Manage and optimize database systems for performance and reliability.",
    },
    {
        "id": "job_44",
        "title": "Blockchain Developer",
        "company": "ChainBuild",
        "location": "Remote",
        "remote": True,
        "skills": ["solidity", "javascript", "api", "python", "security"],
        "description": "Build smart contracts and decentralized applications on Ethereum.",
    },
    {
        "id": "job_45",
        "title": "Game Developer",
        "company": "PlayForge Studios",
        "location": "Los Angeles, CA",
        "remote": False,
        "skills": ["c#", "unity", "game design", "testing", "git"],
        "description": "Develop gameplay mechanics and systems for mobile and PC games.",
    },
    # ── HR / People ───────────────────────────────────────────────
    {
        "id": "job_46",
        "title": "HR Generalist",
        "company": "PeopleFirst",
        "location": "Chicago, IL",
        "remote": False,
        "skills": [
            "hr management",
            "recruiting",
            "communication",
            "excel",
            "compliance",
        ],
        "description": "Support employee lifecycle processes from hiring to offboarding.",
    },
    {
        "id": "job_47",
        "title": "Technical Recruiter",
        "company": "TalentBridge",
        "location": "Remote",
        "remote": True,
        "skills": [
            "recruiting",
            "communication",
            "stakeholder management",
            "analytics",
            "sourcing",
        ],
        "description": "Source and hire top engineering talent for high-growth tech companies.",
    },
    # ── Content / Writing ─────────────────────────────────────────
    {
        "id": "job_48",
        "title": "Technical Writer",
        "company": "DocuCraft",
        "location": "Remote",
        "remote": True,
        "skills": ["technical writing", "api", "html", "git", "communication"],
        "description": "Write and maintain API documentation, guides, and developer tutorials.",
    },
    {
        "id": "job_49",
        "title": "Copywriter",
        "company": "BrandVoice",
        "location": "New York, NY",
        "remote": False,
        "skills": [
            "copywriting",
            "content strategy",
            "seo",
            "communication",
            "social media",
        ],
        "description": "Write persuasive copy for ads, landing pages, and email campaigns.",
    },
    # ── Education / Training ──────────────────────────────────────
    {
        "id": "job_50",
        "title": "Instructional Designer",
        "company": "LearnForward",
        "location": "Remote",
        "remote": True,
        "skills": [
            "instructional design",
            "communication",
            "analytics",
            "content strategy",
            "prototyping",
        ],
        "description": "Design online courses and training programs for enterprise clients.",
    },
    {
        "id": "job_51",
        "title": "Developer Advocate",
        "company": "DevRel Inc",
        "location": "Remote",
        "remote": True,
        "skills": ["python", "api", "technical writing", "communication", "git"],
        "description": "Create tutorials, speak at conferences, and support the developer community.",
    },
    # ── Entry-level / Internship-Adjacent ─────────────────────────
    {
        "id": "job_52",
        "title": "IT Support Specialist",
        "company": "FixIT Solutions",
        "location": "Houston, TX",
        "remote": False,
        "skills": ["troubleshooting", "networking", "linux", "communication", "excel"],
        "description": "Provide desktop and network support for a mid-size corporate office.",
    },
    {
        "id": "job_53",
        "title": "Junior Data Analyst",
        "company": "NumberCrunch",
        "location": "Remote",
        "remote": True,
        "skills": ["excel", "sql", "statistics", "reporting", "python"],
        "description": "Assist the analytics team with data cleaning, reporting, and basic analysis.",
    },
    {
        "id": "job_54",
        "title": "Junior Frontend Developer",
        "company": "WebStart",
        "location": "Remote",
        "remote": True,
        "skills": ["html", "css", "javascript", "git", "react"],
        "description": "Build and maintain UI components under guidance from senior engineers.",
    },
]


def get_all_jobs():
    """Return the full list of job listings."""
    return JOBS


def find_job_by_id(job_id):
    """Return a single job dict by ID, or None."""
    return next((j for j in JOBS if j["id"] == job_id), None)
